# Generated by Django 5.2.4 on 2025-07-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_email_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
