# Generated by Django 5.2.4 on 2025-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
